import type { Metadata } from "next";
import { Geist, Poppins, Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--poppins-font",
  subsets: ['latin'],
  display: 'block'
})

const geist = Geist({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--geist-font",
  subsets: ['latin']
})

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--inter-font",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Mohd Usman | Software Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} ${geist.variable}`}
      >
        {children}
        <Toaster/>
      </body>
    </html>
  );
}
