import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from 'components/Navbar'
import { AiOutlineTwitter, AiFillGithub } from 'react-icons/ai'
import { HiOutlineMail } from 'react-icons/hi'
import { GrReactjs } from 'react-icons/gr'
import { FaNodeJs } from 'react-icons/fa'
import { SiJavascript } from 'react-icons/si'
import { TbBrandNextjs } from 'react-icons/tb'
import {MdKeyboardArrowUp} from 'react-icons/md'
import {IoMdArrowDropup} from 'react-icons/io'
import LandingPage from 'components/LandingPage'
import AboutSection from 'components/AboutSection'
import Skills from 'components/Skills'
import Projects from 'components/Projects'
import ContactSection from 'components/ContactSection'
import Social from 'components/Social'
const inter = Inter({ subsets: ['latin'] })

export default function Home({name}) {
  return (
    <>
      <Head>
        <title>Mohd Usman - Full Stack Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="theme-color" content="#2D2F33" ></meta>
      </Head>
      <Navbar/>
      <LandingPage/>
      <AboutSection/>
      <Skills />
      <Projects/>
      <ContactSection/>
      <Social/>
      <a href="#" className="w-6 h-6 bg-[#73F8AB] rounded-full border hover:border-[#73F8AB] hover:text-[#73F8AB] fixed bottom-3 right-3 flex justify-center items-center hover:bg-transparent cursor-pointer"><MdKeyboardArrowUp className='text-3xl' /></a>
    </>
  )
}
