import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from 'components/Navbar'
import { AiOutlineTwitter, AiFillGithub } from 'react-icons/ai'
import { HiOutlineMail } from 'react-icons/hi'
import { GrReactjs } from 'react-icons/gr'
import { FaNodeJs } from 'react-icons/fa'
import { SiJavascript } from 'react-icons/si'
import { TbBrandNextjs } from 'react-icons/tb'
import {MdOutlineMenuOpen} from 'react-icons/md'
import LandingPage from 'components/LandingPage'
import AboutSection from 'components/AboutSection'
import Skills from 'components/Skills'
import Projects from 'components/Projects'
import ContactSection from 'components/ContactSection'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <LandingPage/>
      <AboutSection/>
      <Skills />
      <Projects/>
      <ContactSection/>
    </>
  )
}
